---
title: "Models"
author: "Rachael Bucci, Alexander Carr, Grant Hershman, Luca Milletti, Emma Mirabelli"
date: "5/4/2022"
output: html_document
---

```{r, warning = FALSE, echo = FALSE, message = FALSE}
# Importing the necessary packages
library(chron)
library(caret)
library(e1071)
library(dplyr)
library(stringr)
library(ROCR)
library(pROC)
```

## Data Cleaning

```{r, warning = FALSE}
# Importing the two datasets
movies_orig <- read.csv("data/movies_metadata.csv", sep = ",", header = T)

# Extracting the columns for analysis
movies_new <- data.frame(movies_orig$original_title,movies_orig$belongs_to_collection,as.numeric(movies_orig$budget), as.numeric(movies_orig$revenue), as.numeric(movies_orig$popularity), movies_orig$original_language, movies_orig$runtime, as.Date(chron(movies_orig$release_date)), movies_orig$genres)
movies_new <- setNames(movies_new, c("original_title","belongs_to_collection","budget","revenue","popularity","original_language","runtime","release_date","genres"))

# Cleaning the data
movies_intermediate <- na.omit(movies_new)
movies_intermediate <- filter(movies_intermediate, movies_intermediate$revenue > 0 & movies_intermediate$budget > 0)
movies <- filter(movies_intermediate, movies_intermediate$release_date >= as.Date("1950-01-01", format = "%Y-%m-%d"))
movies[,"profit_percentage"] <- movies$revenue / movies$budget

# Creating dummy variables for success, language, and series
movies$isSuccess <- ifelse(movies$profit_percentage > 3, 1, 0)
movies$isEN <- ifelse(movies$original_language == "en", 1, 0)
movies$isCollection <- ifelse(movies$belongs_to_collection == "", 0, 1)

# Creating dummy variables for genre
searchGenres <- c("Comedy", "Science Fiction", "Horror", "Romance", "Action", "Thriller", "Drama", "Mystery", "Crime", "Animation", "Adventure", "Fantasy")
movies["Comedy"] <- c(0)
movies["Science Fiction"] <- c(0)
movies["Horror"] <- c(0)
movies["Romance"] <- c(0)
movies["Action"] <- c(0)
movies["Thriller"] <- c(0)
movies["Drama"] <- c(0)
movies["Mystery"] <- c(0)
movies["Crime"] <- c(0)
movies["Animation"] <- c(0)
movies["Adventure"] <- c(0)
movies["Fantasy"] <- c(0)
for (i in searchGenres) {
  for (j in movies$genres) {
    if (str_detect(j, i)) {
      movies[i][match(j, movies$genres),] <- 1
    }
    else {
      movies[i][match(j, movies$genres),] <- 0
    }
  }
}

# Setting up the training and validation data
set.seed(13)
train <- createDataPartition(y = movies$isSuccess, p = .90, list = FALSE)
movies.train <- movies[train,]
movies.test <- movies[-train,]
movies.ctrl <- trainControl(method = "cv", number = 10)
```

## Logistic Regression

```{r, warning = FALSE}
# Training and testing a logistic regression model on the movie dataset
movies.lr <- train(isSuccess ~ budget + popularity + runtime + isEN + isCollection + Comedy + `Science Fiction` + Horror + Romance + Action + Thriller + Drama + Mystery + Crime + Animation + Adventure + Fantasy, data = movies.train, method = "glm", trControl = movies.ctrl)
movies.lr.predict <- predict(movies.lr, newdata = movies.test)
movies.lr.predict.bin <- ifelse(movies.lr.predict > 0.5, 1, 0)
confusionMatrix(as.factor(movies.lr.predict.bin), reference = as.factor(movies.test$isSuccess))
```

## k-Nearest Neighbor

```{r, warning = FALSE}
# Training and testing a k-nearest neighbor model on the movie dataset
movies.knn <- train(isSuccess ~ budget + popularity + runtime + isEN + isCollection + Comedy + `Science Fiction` + Horror + Romance + Action + Thriller + Drama + Mystery + Crime + Animation + Adventure + Fantasy, data = movies.train, method = "knn", trControl = movies.ctrl)
movies.knn.predict <- predict(movies.knn, newdata = movies.test)
movies.knn.predict.bin <- ifelse(movies.knn.predict > 0.5, 1, 0)
confusionMatrix(as.factor(movies.knn.predict.bin), reference = as.factor(movies.test$isSuccess))
```

## Support Vector Machine

```{r, warning = FALSE}
# Training and testing a support vector machine model on the movie dataset
movies.svm <- train(isSuccess ~ budget + popularity + runtime + isEN + isCollection + Comedy + `Science Fiction` + Horror + Romance + Action + Thriller + Drama + Mystery + Crime + Animation + Adventure + Fantasy, data = movies.train, method = "svmLinear", trControl = movies.ctrl)
movies.svm.predict <- predict(movies.svm, newdata = movies.test)
movies.svm.predict.bin <- ifelse(movies.svm.predict > 0.5, 1, 0)
confusionMatrix(as.factor(movies.svm.predict.bin), reference = as.factor(movies.test$isSuccess))
```

## Random Forest

```{r, warning = FALSE}
# Training and testing a random forest model on the movie dataset
movies.rf <- train(isSuccess ~ budget + popularity + runtime + isEN + isCollection + Comedy + `Science Fiction` + Horror + Romance + Action + Thriller + Drama + Mystery + Crime + Animation + Adventure + Fantasy, data = movies.train, method = "rf", trControl = movies.ctrl)
movies.rf.predict <- predict(movies.rf, newdata = movies.test)
movies.rf.predict.bin <- ifelse(movies.rf.predict > 0.5, 1, 0)
confusionMatrix(as.factor(movies.rf.predict.bin), reference = as.factor(movies.test$isSuccess))
```

## ROC Plot

```{r, warning = FALSE}
# Generating the values needed for the ROC curves
movies.lr.rocrpred <- prediction(movies.lr.predict, movies.test$isSuccess)
movies.lr.rocrperf <- performance(movies.lr.rocrpred, "tpr", "fpr")
movies.knn.rocrpred <- prediction(movies.knn.predict, movies.test$isSuccess)
movies.knn.rocrperf <- performance(movies.knn.rocrpred, "tpr", "fpr")
movies.svm.rocrpred <- prediction(as.numeric(movies.svm.predict), movies.test$isSuccess)
movies.svm.rocrperf <- performance(movies.svm.rocrpred, "tpr", "fpr")
movies.rf.rocrpred <- prediction(as.numeric(movies.rf.predict), movies.test$isSuccess)
movies.rf.rocrperf <- performance(movies.rf.rocrpred, "tpr", "fpr")

# Plotting the ROC curves
plot(movies.lr.rocrperf, col = 3, text.adj = c(-0.2, 1.7), main = "ROC Curve")
plot(movies.knn.rocrperf, col = 4, add = TRUE)
plot(movies.svm.rocrperf, col = 5, add = TRUE)
plot(movies.rf.rocrperf, col = 6, add = TRUE)
legend("bottomright", inset = 0.05, legend = c("Logistic Regression", "k-Nearest Neighbor", "Support Vector Machine", "Random Forest"), lty = c(1, 1, 1, 1), col = c(3, 4, 5, 6))
```
## AUC Calculations

```{r, warning = FALSE}
movies.lr.auc <- auc(movies.test$isSuccess, movies.lr.predict)
movies.lr.auc
movies.knn.auc <- auc(movies.test$isSuccess, movies.knn.predict)
movies.knn.auc
movies.svm.auc <- auc(movies.test$isSuccess, movies.svm.predict)
movies.svm.auc
movies.rf.auc <- auc(movies.test$isSuccess, movies.rf.predict)
movies.rf.auc
```

## Variable Analysis

```{r, warning = FALSE}
summary(movies.lr)
```
>>>>>>> svm
